export const categories = [
    'Youtube',
    'IT',
    'School',
    'Music',
    'Animals',
    'Books',
    'Social Media',
    'Horoscopes',
    'Politics',
    'Netflix',
    'World',
    'Humour',
    'Men',
    'Women',
    'Comics',
    'Magic',
    'Style',
    'Copypasta',
    'Science',
    'Sport',
    'Health',
    'Stars',
    'Fantasy',
    'Lifestyle',
    'TV Series',
    'Food',
    'Automotive',
    'Video Games',
    'History',
    'Internet',
    'Cartoons',
    'Anime',
    'Nature',
    'Fairy tales',
    'Psychology',
]
